source 'https://github.com/CocoaPods/Specs.git'

# ignoring warning from pods
inhibit_all_warnings!

target "PhotoBrowserDemo" do

pod 'SDWebImage', '~> 4.0.0-beta2'
pod 'DACircularProgress'
pod 'pop'

end
